spring:
  application:
    name: banksystem
  datasource:
    url: jdbc:mysql://localhost:3306/banksystem?createDatabaseIfNotExist=true
    username: root
    password: MyPassword!!!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    baseline-on-migrate: true

app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 604800000